# Generated by Django 6.1.1 on 2026-09-06 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(blank=True, max_length=255)),
                ('forma', models.CharField(max_length=20)),
                ('forma_uzasadnienie', models.TextField()),
                ('argumentacja', models.CharField(max_length=20)),
                ('argumentacja_uzasadnienie', models.TextField()),
                ('jezyk', models.CharField(max_length=20)),
                ('jezyk_uzasadnienie', models.TextField()),
                ('struktura', models.CharField(max_length=20)),
                ('struktura_uzasadnienie', models.TextField()),
                ('punkty', models.PositiveSmallIntegerField()),
                ('ocena', models.PositiveSmallIntegerField()),
                ('utworzono', models.DateTimeField(auto_now_add=True)),
                ('nauczyciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wyniki_oceniania', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-utworzono'],
            },
        ),
    ]
